// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjNvMpvq3XJRfPTf8Di063pV46jeG1GY',
    appId: '1:757092363572:web:10f3f504474db0f34a8961',
    messagingSenderId: '757092363572',
    projectId: 'language-learning-app-6a165',
    authDomain: 'language-learning-app-6a165.firebaseapp.com',
    storageBucket: 'language-learning-app-6a165.firebasestorage.app',
    measurementId: 'G-26G37KXB6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLw3G0O-mYDF2bVhZj7pvhLWekvcq_FPk',
    appId: '1:757092363572:android:64cbe3bd0b7ef9744a8961',
    messagingSenderId: '757092363572',
    projectId: 'language-learning-app-6a165',
    storageBucket: 'language-learning-app-6a165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgspu-KFRtQGyQEzgbfvEFHAdmQmzud3w',
    appId: '1:757092363572:ios:94132d62ad4b78c14a8961',
    messagingSenderId: '757092363572',
    projectId: 'language-learning-app-6a165',
    storageBucket: 'language-learning-app-6a165.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgspu-KFRtQGyQEzgbfvEFHAdmQmzud3w',
    appId: '1:757092363572:ios:94132d62ad4b78c14a8961',
    messagingSenderId: '757092363572',
    projectId: 'language-learning-app-6a165',
    storageBucket: 'language-learning-app-6a165.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjNvMpvq3XJRfPTf8Di063pV46jeG1GY',
    appId: '1:757092363572:web:ab14e667549f24dc4a8961',
    messagingSenderId: '757092363572',
    projectId: 'language-learning-app-6a165',
    authDomain: 'language-learning-app-6a165.firebaseapp.com',
    storageBucket: 'language-learning-app-6a165.firebasestorage.app',
    measurementId: 'G-P1ESJVTW6N',
  );
}
